import type { Metadata } from "next";
import EmotionCacheProvider from "./emotion-cache";
import ThemeProvider from "./ThemeProvider";
import Header from "./components/Header/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        />
      </head>
      <body>
        <EmotionCacheProvider>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </EmotionCacheProvider>
      </body>
    </html>
  );
}
